package alpha1;

import java.awt.Graphics;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class ShowImage extends javax.swing.JDialog implements MouseListener {

	
	private static final long serialVersionUID = 1L;
	 
	static  String imagePath1=null;
	static  String imagePath2=null;
	static  String imagePath3=null;
	static int select=0;
	static int flag=0;
	static int count=0;
	static int temp=0;


	public ShowImage(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		
	}
	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	
	private void initComponents() {

		jFrame1 = new javax.swing.JFrame();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
		jFrame1.getContentPane().setLayout(jFrame1Layout);
	
		
		jFrame1Layout.setHorizontalGroup(
				jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 400, Short.MAX_VALUE)
				);
		jFrame1Layout.setVerticalGroup(
				jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 300, Short.MAX_VALUE)
				);

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jButton1.setText("Browse");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		
		

		jButton2.setText("Perform");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("Save");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jTextField1.setText("\t");
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Image Negatives", "Log Transformation", "Power-Law Transformation", "Histogram Equalization","Histogram Specification","Edge Detection by Sobel Operator","Edge Detection by Laplace Operator","Thresholding" }));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});
		
		
		
		



		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);
		jLabel2.setText("Parameters");
		jLabel1.setText("jLabel1");
		 
		  

		
		

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1)
								.addGroup(layout.createSequentialGroup()
										.addGap(189, 189, 189)
										.addComponent(jButton1)
										.addGap(35, 35, 35)
										.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(48, 48, 48)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addGap(10, 10, 10)
														.addComponent(jLabel2))
														.addGroup(layout.createSequentialGroup()
																.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(70, 70, 70)
																.addComponent(jButton2)))))
																.addGap(0,340, Short.MAX_VALUE))
																.addGroup(layout.createSequentialGroup()
																		.addGap(363, 363, 363)
																		.addComponent(jButton3)
																		.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(586, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButton2))
										.addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addGap(68, 68, 68)
														.addComponent(jLabel1))
														.addGroup(layout.createSequentialGroup()
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jLabel2)
																.addGap(18, 18, 18)
																.addComponent(jButton3)))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
				);


		pack();

	}
	
	
	
	
	
	

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
	{                                         
		JFileChooser chooser = new JFileChooser();
		chooser.showOpenDialog(null);
		File input = chooser.getSelectedFile();

		
		
		
		if(select==4 && count!=0)
		{
			imagePath2 = input.getAbsolutePath();
		}
		else
		{
			imagePath1 = input.getAbsolutePath();
			imagePath2=null;
			imagePath3=null;
			count++;
		}

		repaint();
	}                                        

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		String text =null;
		double gamaValue=0;
		
		if(imagePath1!=null)
			imagePath1 = imagePath1.replace("\\", "/");
		if(imagePath2!=null)
			imagePath2 = imagePath2.replace("\\", "/");
		 
		text =jTextField1.getText(); 
		String parameter = text.trim();
		
		if(parameter.length()!=0)
			gamaValue=Double.parseDouble(parameter);

		
		
		
		Caller clr =new Caller();
		 try {
			imagePath3 =clr.getCaller(imagePath1, imagePath2, select,gamaValue);
		} catch (IOException e) {
			
			e.printStackTrace();
		}
		
		repaint();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		PointerInfo a = MouseInfo.getPointerInfo();
	    Point b = a.getLocation();
	    int x = (int) b.getX();
	    int y = (int) b.getY();
	    System.out.print("Y: "+y);
	    System.out.print("X: "+x+"\n");
	    MouseListener ms=null;
		   //MouseEvent e = null;
		   jFrame1.addMouseListener(ms);
	

	}
	
	
	
	
	

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		select = jComboBox1.getSelectedIndex();

	}


	public void paint(Graphics g)
	{
		super.paint(g);
		
	
		if(imagePath1!=null)
		{
			File file = new File(imagePath1);
			BufferedImage image=null;
			
			try 
			{
				image = ImageIO.read(file);
			} 
			catch (IOException e) 
			{
				System.out.println("Error:"+e.getMessage());
			}
			
			

			g.drawImage(image,10,39,375,375, null);
			
		}

		if(imagePath2!=null)
		{

			File file1 = new File(imagePath2);
			BufferedImage image2=null;
			
			try
			{
				image2=ImageIO.read(file1);
			}
			catch(IOException e)
			{
				System.out.println("Error:"+e.getMessage());
			}
			g.drawImage(image2,393,39,375,375, null);
		}


		if(imagePath3!=null)
		{
			
			File file3 = new File(imagePath3);
			BufferedImage image3=null;
	
			try
			{
				image3=ImageIO.read(file3);
			}
			catch(IOException e)
			{
				System.out.println("Error:"+e.getMessage());
			}
			g.drawImage(image3,776,39,375,375, null);
		}


	}


	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ShowImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ShowImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ShowImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ShowImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		

		/*
		 * Create and display the dialog
		 */
		
		
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				ShowImage dialog = new ShowImage(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {

					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);

			}
		});
		
		
	  
	}



	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JFrame jFrame1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration


	@Override
	public void mouseClicked(MouseEvent e) {
		System.out.println("here");
		
		
	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}


	
}
